### ISSUE TITLE
alminer.target returns DALQueryError

### ISSUE THREAD

**Issue by gica3618** [emerge-erc/ALminer#5] opened 2023-07-03 09:10 UTC
I encountered a strange error when doing a simple query with ALminer version 0.1.3. The query `alminer.target(sources='HD143006')` fails with the following error message: "DALQueryError: ORA-01489: result of string concatenation is too long ORA-01489: result of string concatenation is too long". Is there a way to fix this?

**Comment by gica3618** [comment] 2023-07-03 09:15
Just realised that the error message is the same as in issue #4

**Comment by gica3618** [comment] 2023-07-20 03:37
This seems in problem with pyvo, so I opened an issue there: [https://github.com/astropy/pyvo/issues/458](https://github.com/astropy/pyvo/issues/458)

**Comment by gica3618** [comment] 2023-07-21 00:21
This issue is discussed here: [https://github.com/astropy/astroquery/issues/2726](https://github.com/astropy/astroquery/issues/2726)

**Comment by aida-ahmadi** [comment] 2023-07-24 09:34
Hi! Apologies for seeing this so late. Indeed as the Astropy team mentioned, the issue is upstream and I believe the ALMA team is aware of it. The issue pertains to certain projects so if those fall within your search criteria, the entire query will crash. One way to get around this at the moment is to figure out where exactly this happens and to exclude the projects that cause the issue. 

For your example, the issue is with project 2016.1.00484.L. I found this out by looking at all the projects corresponding to your target on the web interface of the ALMA Science Archive and querying the project codes with ALminer keysearch function to see for which projects the query crashes (i.e. `alminer.keysearch({'proposal_id':['2016.1.00484.L']})` will crash with the same error).

Once you know which projects to exclude, you can do the following:

1) Get the query string from alminer.target function:

`full_query = alminer.target('HD143006', print_query=True)`

The output before the query crashes is:

> Your query is: SELECT * FROM ivoa.ObsCore WHERE (1 = INTERSECTS(CIRCLE('ICRS',239.65380261662,-22.95422793311,0.016666666666666666), s_region) OR 1 = CONTAINS(POINT('ICRS',239.65380261662,-22.95422793311), s_region)) AND data_rights LIKE '%Public%'

2) Copy the query string and add the following line to the end: `AND proposal_id NOT LIKE '2016.1.00484.L'`, so the full query string is:

`query_str = f"""SELECT * FROM ivoa.ObsCore WHERE (1 = INTERSECTS(CIRCLE('ICRS',239.65380261662,-22.95422793311,0.016666666666666666), s_region) OR 1 = CONTAINS(POINT('ICRS',239.65380261662,-22.95422793311), s_region)) AND data_rights LIKE '%Public%' AND proposal_id NOT LIKE '2016.1.00484.L'"""`

3) Run the query & convert the results to ALminer format:

```
adjusted_query = alminer.run_query(query_str)
adjusted_query_alminer = alminer.filter_results(adjusted_query)
```

Now `adjusted_query_alminer` is a DataFrame in ALminer format and you can use all the ALminer plotting functionalities with it. Just beware that you are excluding project 2016.1.00484.L from your results. 

Hope this helps you in the meanwhile until the issue gets fixed upstream.

**Comment by gica3618** [comment] 2023-07-31 03:25
Thanks @aida-ahmadi, I will give it a try!

**Comment by aida-ahmadi** [comment] 2023-10-10 13:43
Hi @gica3618, this issue has been solved upstream in the most recent release of the ALMA archive. So I will close this ticket, but please feel free to open a new one if you encounter other issues.

**Closed as completed by aida-ahmadi** 2023-10-10 13:43 UTC
Labels: upstream
